# 画像のURL
URL:
  YABAIWAYO: https://raw.githubusercontent.com/smicle/smicle-line-bot/assets/assets/%E3%83%A4%E3%83%90%E3%82%A4%E3%82%8F%E3%82%88%EF%BC%81.png
  YABAIDESUNE: https://raw.githubusercontent.com/smicle/smicle-line-bot/assets/assets/%E3%82%84%E3%81%B0%E3%81%84%E3%81%A7%E3%81%99%E3%81%AD%E2%98%86.png
  METTYAYAMU: https://raw.githubusercontent.com/smicle/smicle-line-bot/assets/assets/%E3%82%84%E3%82%80.jpg

# スプレッドシートのリンク
SPREAD_SHEETS: https://docs.google.com/spreadsheets/d/1ACRIqT95fIjMhyzibSxO6MXCGZYQIcDzvnMsn7_t94k/edit#gid=0
